// Generated by CoffeeScript 1.6.1

define(function(require) {
  var $, Util, content, title;
  module("dialog");
  Util = require("util");
  $ = require("jquery");
  title = "title";
  content = "content";
  return $(function() {
    test("API", function() {
      ok(Util.dialog);
      ok(Util.dialog.open);
      ok(Util.dialog.close);
      strictEqual(typeof Util.dialog, "function");
      strictEqual(typeof Util.dialog.open, "function");
      return strictEqual(typeof Util.dialog.close, "function");
    });
    return test("dialog.open", function() {
      Util.dialog({
        title: title,
        content: content
      });
      ok($("#zonda-util-dialog")[0]);
      return ok(true);
    });
  });
});
