// Generated by CoffeeScript 1.6.1

define(function(require) {
  var Util, dialog;
  module("dialog");
  Util = require("util");
  dialog = Util.dialog;
  return test("API", function() {
    ok(dialog);
    ok(dialog.open);
    ok(dialog.close);
    strictEqual(typeof dialog, "function");
    strictEqual(typeof dialog.open, "function");
    return strictEqual(typeof dialog.close, "function");
  });
});
