// Generated by CoffeeScript 1.6.1

define(function(require) {
  var StateMachine, Util, list_state, list_view, mainStateMachine, main_state, main_view, sub_state, sub_view;
  module("StateMachine");
  Util = require("util");
  StateMachine = Util.StateMachine;
  mainStateMachine = new StateMachine();
  main_state = false;
  list_state = false;
  sub_state = false;
  main_view = {
    activate: function() {
      return main_state = true;
    },
    deactivate: function() {
      return main_state = false;
    }
  };
  list_view = {
    activate: function() {
      return list_state = true;
    },
    deactivate: function() {
      return list_state = false;
    }
  };
  sub_view = {
    activate: function() {
      return sub_state = true;
    },
    deactivate: function() {
      return sub_state = false;
    }
  };
  mainStateMachine.add(main_view);
  mainStateMachine.add(list_view);
  mainStateMachine.add(sub_view);
  test("API", function() {
    ok(StateMachine);
    return strictEqual(typeof StateMachine, "function");
  });
  test("Instance API", function() {
    ok(mainStateMachine);
    return strictEqual(typeof mainStateMachine, "object");
  });
  test("Add of Instance API", function() {
    ok(mainStateMachine.add);
    return strictEqual(typeof mainStateMachine.add, "function");
  });
  test("Active::main_view", function() {
    main_view.active();
    ok(main_state);
    strictEqual(list_state, false);
    return strictEqual(sub_state, false);
  });
  test("Active::list_view", function() {
    list_view.active();
    ok(list_state);
    strictEqual(main_state, false);
    return strictEqual(sub_state, false);
  });
  test("Active::sub_view", function() {
    sub_view.active();
    ok(sub_state);
    strictEqual(main_state, false);
    return strictEqual(list_state, false);
  });
  return test("other StateMachine", function() {
    var a_state, a_view, b_state, b_view, c_state, c_view, otherStateMachine;
    otherStateMachine = new StateMachine();
    a_state = false;
    b_state = false;
    c_state = false;
    a_view = {
      activate: function() {
        return a_state = true;
      },
      deactivate: function() {
        return a_state = false;
      }
    };
    b_view = {
      activate: function() {
        return b_state = true;
      },
      deactivate: function() {
        return b_state = false;
      }
    };
    c_view = {
      activate: function() {
        return c_state = true;
      },
      deactivate: function() {
        return c_state = false;
      }
    };
    otherStateMachine.add(a_view);
    otherStateMachine.add(b_view);
    otherStateMachine.add(c_view);
    a_view.active();
    ok(a_state);
    strictEqual(b_state, false);
    strictEqual(c_state, false);
    sub_view.active();
    ok(sub_state);
    strictEqual(main_state, false);
    return strictEqual(list_state, false);
  });
});
