// Generated by CoffeeScript 1.6.1
var colors, combo, fs, listVendor, name, package_info, path, project_dir, vendor_list, zonda_vendor_dir, _vendor_content;

fs = require("fs");

path = require("path");

colors = require("/usr/local/lib/node_modules/colors");

listVendor = require("./listVendor");

project_dir = path.resolve('./', '../');

zonda_vendor_dir = "vendor/Zonda/vendor";

vendor_list = listVendor("" + project_dir + "/" + zonda_vendor_dir, zonda_vendor_dir);

fs.writeFileSync("" + project_dir + "/dist/vendor-combo.js", "");

combo = "" + project_dir + "/dist/vendor-combo.js";

package_info = fs.readFileSync("" + project_dir + "/etc/package.json", "utf8");

package_info = JSON.parse(package_info);

for (name in package_info.dependencies) {
  _vendor_content = fs.readFileSync("" + project_dir + "/" + vendor_list.alias[name] + ".js");
  fs.appendFileSync(combo, _vendor_content);
}
