// Generated by CoffeeScript 1.6.1
var alias, dependencies, env, fs, listVendor, package_info, path, project_dir, vendor_list, zonda_vendor_dir;

fs = require("fs");

path = require("path");

listVendor = require("./listVendor");

project_dir = path.resolve('./', '../');

zonda_vendor_dir = "vendor/Zonda/vendor";

vendor_list = listVendor("" + project_dir + "/" + zonda_vendor_dir, zonda_vendor_dir);

alias = JSON.stringify(vendor_list.alias);

dependencies = JSON.stringify(vendor_list.dependencies);

env = "seajs.config({\n  base: \"/assets\",\n  charset: \"utf-8\",\n  alias: " + alias + "\n});";

fs.writeFileSync("" + project_dir + "/etc/env.js", env);

package_info = "{\n    \"name\": \"dist\",\n    \"root\": \"/assets\",\n    \"dependencies\": " + dependencies + ",\n    \"output\": {\n        \"app.js\" : \".\"\n    }\n}";

fs.writeFileSync("" + project_dir + "/etc/package.json", package_info);
