// Generated by CoffeeScript 1.6.3
var CONFIG, Mustache, colors, deploy_dir, exec, fs, path, project_dir, res_content, tpl;

require("js-yaml");

fs = require("fs");

path = require("path");

colors = require("colors");

Mustache = require("mustache");

exec = require('child_process').exec;

console.log("\n\n Zonda Tool".bold + ":  Deploy...");

project_dir = path.resolve('./', '../');

CONFIG = require("" + project_dir + "/etc/zonda.yml");

tpl = fs.readFileSync("" + project_dir + "/tool/deploy/fragment.html", {
  encoding: "utf8"
});

res_content = Mustache.render(tpl, {
  CONFIG: CONFIG
});

deploy_dir = path.resolve(project_dir, CONFIG.deploy_dir);

fs.writeFileSync("" + deploy_dir + "/" + CONFIG.deploy_file, res_content);

console.log("\n\n Zonda Tool".bold + " >> " + ("Generate framework-" + CONFIG.version + ".js") + " Success!\n".bold.yellow);
