// Generated by CoffeeScript 1.6.1
var colors, exec, fs, path, project_dir;

colors = require("/usr/local/lib/node_modules/colors");

fs = require("fs");

path = require("path");

exec = require("child_process").exec;

project_dir = path.resolve("./", "../");

module.exports = function(name, version, app_root) {
  var module_dir, spm_build_config;
  module_dir = path.resolve("" + project_dir + "/vendor/Zonda/vendor/" + name + "/" + version);
  console.log("Update the vendor: " + ("" + name + "/" + version).green);
  if (fs.existsSync("" + module_dir + "/package.json")) {
    spm_build_config = "{\n  \"name\": \"" + name + "\",\n  \"root\": \"" + app_root + "/vendor/Zonda/vendor\",\n  \"version\": \"" + version + "\",\n  \"output\": {\n    \"" + name + ".js\": \".\"\n  },\n  \"sources\": [\"http://module.zonda.dashu.us:22221\"]\n}";
    fs.writeFileSync("" + project_dir + "/vendor/Zonda/vendor/" + name + "/" + version + "/package.json", spm_build_config);
    console.log("Generate the package.json for " + ("" + name + "." + version).green.underline + "\n");
    return exec("cd " + module_dir + " && spm build && cp ./dist/" + name + ".js ./", function(err, stdout, stderr) {
      if (err !== null) {
        console.log("ERROR".red.inverse + "build the " + ("" + name + "." + version).red.underline + " failed!");
        return false;
      }
      return console.log(stdout);
    });
  } else {
    return console.log("WAR".inverse.red + (" vendor " + name).underline + " has no " + "package.json".yellow);
  }
};
