// Generated by CoffeeScript 1.6.2
define(function(require, exports, module) {
  return module.exports = {
    Base64: require("./base64/base64"),
    Dialog: require("./dialog/dialog"),
    StateMachine: require("./stateMachine/stateMachine"),
    Genre: require("./genre/genre"),
    Model: require("./model/model")
  };
});
