// Generated by CoffeeScript 1.6.2
define(function(require, exports, module) {
  return module.exports = {
    StateMachine: require("./StateMachine/StateMachine"),
    base64: require("./base64/base64"),
    dialog: require("./dialog/dialog"),
    message: require("./message/message")
  };
});
