// Generated by CoffeeScript 1.6.3
var colors, exec, fs, mustache, path;

require("js-yaml");

fs = require("fs");

path = require("path");

colors = require("colors");

mustache = require("mustache");

exec = require('child_process').exec;

console.log("\n\n Zonda Tool".bold + ":  Deploy...");
