// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Dialog, Util;

  module("Dialog");
  Util = require("util");
  Dialog = Util.dialog;
  test("API", function() {
    ok(Dialog.open);
    ok(Dialog.close);
    strictEqual(typeof Dialog.open, "function");
    return strictEqual(typeof Dialog.close, "function");
  });
  test("Dialog Render", function() {
    Dialog({
      title: "small",
      content: "big",
      button: {
        "hehe": function() {}
      }
    }).open();
    ok(Dialog.$dom[0]);
    strictEqual(Dialog.$dom.find(".modal-header h3").text(), "small");
    ok(/big/.test(Dialog.$dom.find(".modal-body").text()));
    ok(/hehe/.test(Dialog.$dom.find(".modal-footer button[id]").text()));
    return Dialog.close();
  });
  test("Dialog Style", function() {
    Dialog.close();
    Dialog({
      title: "small",
      content: "big",
      "class": "haha",
      button: {
        "hehe": function() {}
      }
    }).open();
    ok(Dialog.$dom.hasClass("haha"));
    return Dialog.close();
  });
  return test("Dialog button callback", function() {
    var num;

    Dialog.close();
    num = 1;
    Dialog({
      title: "small",
      content: "big",
      "class": "haha",
      button: {
        "hehe": function() {
          num = 2;
          return start();
        }
      }
    }).open();
    stop();
    Dialog.$dom.find(".modal-footer button").trigger("click");
    strictEqual(num, 2);
    return Dialog.close();
  });
});
