// Generated by CoffeeScript 1.6.3
define(function(require) {
  var Mustache, Util, form_html;
  Util = require("util");
  Mustache = require("mustache");
  form_html = "<form name=\"test-form\" class=\"form-horizontal\">\n  <fieldset>\n   <legend>Legend</legend>\n\n    <div class=\"form-group\">\n      <label for=\"test-text\" class=\"col-lg-2 control-label\">text</label>\n      <div class=\"col-lg-5\">\n        <input id=\"test-text\" class=\"form-control\" type=\"text\" name=\"test-text\" />\n      </div>\n    </div>\n\n    <div class=\"form-group\">\n      <label class=\"col-lg-2 control-label\" for=\"test-password\">password</label>\n      <div class=\"col-lg-5\">\n        <input id=\"test-password\" class=\"form-control\" type=\"password\" name=\"test-password\" />\n      </div>\n    </div>\n\n    <div class=\"form-group\">\n      <label class=\"col-lg-2 control-label\" for=\"test-password-retype\">pd:retype</label>\n      <div class=\"col-lg-5\">\n        <input id=\"test-password-retype\" class=\"form-control\" type=\"password\" name=\"test-password-retype\" />\n      </div>\n    </div>\n\n    <div class=\"form-group\">\n      <div class=\"col-lg-offset-2 col-lg-5\">\n        <div class=\"checkbox\">\n          <label>\n            <input id=\"test-radio\" name=\"test-radio\" type=\"checkbox\"> checkbox\n          </label>\n        </div>\n      </div>\n    </div>\n\n    <div class=\"form-group\">\n      <label class=\"col-lg-2 control-label\" for=\"test-textarea\">textarea</label>\n      <div class=\"col-lg-5\">\n        <textarea id=\"test-textarea\" class=\"form-control\" name=\"test-textarea\" rows=\"3\"></textarea>\n      </div>\n    </div>\n\n    <div class=\"form-group\">\n      <label class=\"col-lg-2 control-label\" >radio</label>\n      <div class=\"col-lg-5\">\n        <input type=\"radio\" name=\"test-radio\" />\n        <input type=\"radio\" name=\"test-radio\" />\n      </div>\n    </div>\n\n    <select name=\"test-select\">\n      <option value=\"0\">0</option>\n      <option value=\"1\">1</option>\n      <option value=\"2\">2</option>\n    </select>\n\n  </fieldset>\n</form>";
  module("Form");
  return test("API", function() {
    Util.Dialog({
      title: "Form Test",
      content: form_html,
      backdrop: false
    }).open();
    return ok(Util.Form);
  });
});
