// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Message, Util;

  module("Message");
  Util = require("util");
  Message = Util.message;
  return test("API", function() {
    ok(Message.error);
    ok(Message.success);
    ok(Message.tip);
    return ok(Message.loading);
  });
});
