// Generated by CoffeeScript 1.6.2
define(function(require) {
  var API, Model, Util, dog_Model;

  module("Model");
  API = {
    genre: {
      "id~id : @Number": "",
      "variety~var : @String": "",
      "lifetime~life : @Number": "",
      "min-height~min-h : @Number": "",
      "max-height~max-h : @Number": "",
      "wool~wool : @Array": [
        {
          "type~type : @Array": [
            {
              "name~typename : @String": "",
              "id~typeid : @Number": ""
            }
          ],
          "color~color : @Array": [
            {
              "name~colorname : @String": "",
              "id~colorid : @Number": ""
            }
          ]
        }
      ]
    },
    CREATE: {
      url: "/FAKE_CREATE_dog",
      expire: 1
    },
    UPDATE: {
      url: "/FAKE_UPDATE_dog",
      expire: 1
    },
    READ: {
      url: "/FAKE_READ_dog",
      expire: 1300
    },
    READ_LIST: {
      url: "/FAKE_READ_LIST_dog",
      expire: 1300
    },
    DELELE: {
      url: "/FAKE_DELETE_dog",
      expire: 1300
    }
  };
  Util = require("util");
  Model = Util.Model;
  dog_Model = new Model("dog", API);
  return test("API", function() {
    ok(dog_Model.CREATE);
    ok(dog_Model.READ);
    ok(dog_Model.UPDATE);
    return ok(dog_Model.DELELE);
  });
});
