// Generated by CoffeeScript 1.6.3
define(function(require) {
  var Util;
  Util = require("util");
  module("Queue");
  return test("API", function() {
    var queue;
    queue = new Util.Queue("test");
    ok(Util.Queue);
    strictEqual(typeof Util.Queue, "function");
    strictEqual(typeof Util.Queue, "function");
    strictEqual(queue.NAME, "test");
    strictEqual(typeof queue, "object");
    strictEqual(typeof queue.setter, "function");
    return strictEqual(typeof queue.checkAll, "function");
  });
});
