build:
	@./tool/configure.sh
	@./tool/build.framework.sh
	@./tool/build.app.sh

install:
	@./tool/deploy.app.sh

config:
	@./tool/configure.sh

update:
	@./tool/configure.sh
	@./tool/update.vendor.sh

clean:
	@./tool/clean.sh
