// Generated by CoffeeScript 1.6.2
var TPL, app_name, app_root, app_version, deploy_file, framework_version, fs, path, project_dir;

fs = require("fs");

path = require("path");

project_dir = path.resolve('./', '../');

app_version = fs.readFileSync("" + project_dir + "/tool/.app_version", "utf8");

app_root = fs.readFileSync("" + project_dir + "/tool/.app_root", "utf8");

framework_version = fs.readFileSync("" + project_dir + "/tool/.framework_version", "utf8");

deploy_file = fs.readFileSync("" + project_dir + "/tool/.deploy_file", "utf8");

app_name = fs.readFileSync("" + project_dir + "/tool/.app_name", "utf8");

app_version = app_version.replace("\n", "");

app_root = app_root.replace("\n", "");

framework_version = framework_version.replace("\n", "");

deploy_file = deploy_file.replace("\n", "");

app_name = app_name.replace("\n", "");

TPL = "<!DOCTYPE HTML>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0\">\n  <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n  <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\n  <title>" + app_name + "</title>\n  <link rel=\"stylesheet\" href=\"" + app_root + "/dist/dist-" + app_version + ".css\" />\n</head>\n<body>\n</body>\n<script src=\"" + app_root + "/dist/framework-" + framework_version + ".js\" id=\"seajsnode\" data-main=\"" + app_root + "/dist/app-" + app_version + ".js\" ></script>\n</html>";

fs.writeFileSync(deploy_file, TPL);
