// Generated by CoffeeScript 1.6.1
var alias, env, fs, listVendor, path, project_dir, vendor_list, zonda_vendor_dir;

fs = require("fs");

path = require("path");

listVendor = require("./listVendor");

project_dir = path.resolve('./', '../');

zonda_vendor_dir = "vendor/Zonda/vendor";

vendor_list = listVendor("" + project_dir + "/" + zonda_vendor_dir, zonda_vendor_dir);

alias = JSON.stringify(vendor_list.alias);

env = "seajs.config({\n  base: \"/assets\",\n  charset: \"utf-8\",\n  alias: " + alias + "\n});";

fs.writeFileSync("" + project_dir + "/etc/env.js", env);
