// Generated by CoffeeScript 1.6.1
var app, colors, connect, fs, http, port;

connect = require("connect");

http = require("http");

fs = require("fs");

colors = require("colors");

port = 3000;

app = connect().use(connect["static"]("" + __dirname + "/../../"));

http.createServer(app).listen(port);

console.log("> The static server in".inverse + " http://localhost:".green + port + "/test/".red);

fs.writeFileSync("" + __dirname + "/pid.tmp", process.pid, "utf-8");
