// Generated by CoffeeScript 1.4.0
var fileAll;

fileAll = require("./dir");

fileAll("../lib", function(type, dir, depth) {
  console.log(type);
  console.log(dir.name);
  return console.log(depth);
}, 2);
