// Generated by CoffeeScript 1.6.2
define("Zonda/API", [], function(require, exports, module) {
  var API;

  API = {
    dog: require("./genre/dog")
  };
  window.Zonda = {
    API: API
  };
  return module.exports = API;
});
