// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  var Util, b, tpl;
  Util = require("util");
  b = require("./b");
  b();
  tpl = require("./d.tpl");
  return Util.Dialog({
    title: "Welcome~",
    content: "Hi Zonda~"
  }).open();
});
