// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  var Util, b, tpl;
  Util = require("util");
  b = require("./b");
  b();
  tpl = require("./d.tpl");
  Util.Dialog({
    title: "Welcome~",
    content: "Hi Zonda~",
    button: {
      "hehe": function() {
        return alert(1);
      }
    }
  });
  return setTimeout(function() {
    return Util.Dialog.open();
  }, 1300);
});
