// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  var Util;
  Util = require("util");
  return Util.Dialog({
    title: "Welcome~",
    content: "Hi Zonda~"
  }).open();
});
