// Generated by CoffeeScript 1.6.2
define(function(require, exports, module) {
  var datasource, server, sinon;

  require("sinon");
  sinon = window.sinon;
  datasource = require("./datasource");
  server = sinon.sandbox.useFakeServer();
  return module.exports = function(url) {
    server.respondWith(url, function(xhr) {
      var request;

      request = xhr.requestBody;
      console.log("HTTP Request: " + url);
      console.log("HTTP Request: " + request);
      return xhr.respond(200, {
        "Content-Type": "application/json"
      }, JSON.stringify({
        err: null,
        data: datasource[url][request]
      }));
    });
    return server.respond();
  };
});
