// Generated by CoffeeScript 1.6.2
define(function(require, exports, module) {
  var StateMachine, main_state_machine, main_view, view, view_name;

  StateMachine = require("../class/stateMachine");
  main_view = require("./main/main");
  main_state_machine = new StateMachine;
  for (view_name in main_view) {
    view = main_view[view_name];
    main_state_machine.add(view);
  }
  return module.exports = {
    main: main_view
  };
});
