// Generated by CoffeeScript 1.6.2
define(function(require, exports, module) {
  var Backbone, Genre, Http, Model, _;

  _ = require("underscore");
  Backbone = require("backbone");
  Genre = require("../genre/genre");
  Http = require("../http/http");
  Model = (function() {
    function Model(NAME, API) {
      var _this = this;

      this.NAME = NAME;
      this.API = API;
      _.extend(this, Backbone.Events);
      this.genre = new Genre(this.API, "@" + this.NAME);
      if (this.id) {
        this.namespace = "" + this.NAME + ":" + this.id;
      } else {
        this.namespace = "" + this.NAME;
      }
      _.each(this.API, function(detail, act) {
        if (act === "genre") {
          return;
        }
        return _this[act] = function(request) {
          return _this.sync(act, request);
        };
      });
    }

    Model.prototype.sync = function(act, request) {
      if (request !== void 0 && typeof request !== "object") {
        throw "[" + this.NAME + "] Model.sync ERROR: request is not a object!";
      }
      this.genre.inspect(request);
      this.genre.toRemote(request);
      return Http({
        url: this.API[act].url,
        data: request,
        caller: this,
        namespace: "" + this.namespace + ":" + act
      });
    };

    return Model;

  })();
  return module.exports = Model;
});
