// Generated by CoffeeScript 1.6.2
define(function(require, exports, module) {
  var $;

  $ = require("jquery");
  return module.exports = {
    send: {
      activate: function() {
        $("#mail-send-box").fadeIn();
        $("#mail-template-list").fadeIn({
          duration: 500,
          always: function() {
            return $(this).find(".scroll").slideDown("fast");
          }
        });
        return $("#mail-template-variable").fadeIn({
          duration: 500,
          always: function() {
            return $(this).find(".scroll").slideDown("fast");
          }
        });
      },
      deactivate: function() {
        $("#mail-send-box").hide();
        $("#mail-template-list").hide(function() {
          return $(this).find(".scroll").slideUp();
        });
        return $("#mail-template-variable").hide(function() {
          return $(this).find(".scroll").slideUp();
        });
      }
    },
    setting: {
      activate: function() {
        return $("#mail-setting").fadeIn();
      },
      deactivate: function() {
        return $("#mail-setting").hide();
      }
    },
    status: {
      activate: function() {
        return $("#mail-status").fadeIn();
      },
      deactivate: function() {
        return $("#mail-status").hide();
      }
    }
  };
});
